export {default as Home} from './Home'
export {default as About} from './About'
export {default as Error} from './Error'
export {default as Cocktail} from './Cocktail'
export {default as Newsletter} from './Newsletter'
export {default as Landing} from './Landing'